### ISSUE TITLE
Foreach array param then save as 1 record per element

### ISSUE THREAD

**Issue by bakashyn** [quyetdc/techmaster-rails#22]
Hiện tại e đang muốn làm form upload nhiều ảnh 1 lúc, khi upload lên thì mỗi ảnh sẽ đc lưu trong 1 record riêng bằng cách lặp thằng params[:link], name là tên file, desc-album_id-team_id thì dùng chung theo input bên ngoài

khi chạy thì báo lỗi save nilClass của thằng @picture
a xem giups e với @quyetdc 

gem carrierwave

**_View/_form_**

    <%= form_for [:admin, @picture], :html => {multipart: true, :class => 'form-horizontal'} do |f| %>
    <div class="box-body">
        <div class="form-group">

          
          <%= f.label :album, :class => 'control-label col-sm-2' %>
          <div class="col-sm-4">
            <%= f.select "album_id", Album.all.collect {|s| [s.name, s.id]},{include_blank: true},required: true, :class => 'form-control' %>
          </div>

          
          <%= f.label :team, :class => 'control-label col-sm-2' %>
          <div class="col-sm-4">
            <%= f.select "team_id", Team.all.collect {|s| [s.name, s.id]},{include_blank: true}, :class => 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :link, :class => 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.file_field :link, multiple: true, :class => 'form-control', :id => 'imgInp' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :description, :class => 'control-label col-sm-2' %>
          <div class="col-sm-10">
            <%= f.text_area :description, :class => 'form-control' %>
          </div>
        </div>
      </div>
      
      <div class="box-footer">
        <%= link_to admin_pictures_path do %>
            <button class="btn btn-default">Back</button>
        <% end %>
        <%= f.submit nil, :class => 'btn btn-info pull-right' %>
      </div>
      <% end %>

_**controller**_

    def create

      if params[:link]
        picture_amount = 0
        picture_error = []
        params[:link].each { |image|
          @picture = Picture.new(name: image.file.filename, description: params[:description], link: image, album_id: params[:album_id], team_id: params[:team_id])
          @picture.save
        }
      end

      respond_to do |format|
        if @picture.save
          format.html { redirect_to admin_pictures_path, notice: '#{picture_amount} picture was successfully created. Fail: #{picture_error}.' }
          format.json { render :show, status: :created, location: @picture }
        else
          format.html { render :new }
          format.json { render json: @picture.errors, status: :unprocessable_entity }
        end
      end
      end
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:name, :description, :link, :album_id, :team_id)
    end
    end

**Comment by quyetdc** [comment]
okay, nó liên quan tới #18, carrierwave và #10 làm backend. Nên chắc a chưa làm ngay được cho dự án bookstore này

Theo a hiểu thì từ gem carrierwave, nó đang support upload nhiều ảnh như cái link này:
https://github.com/carrierwaveuploader/carrierwave#user-content-multiple-file-uploads

Em đã follow đúng cái tutorial của nó chưa?

**Comment by bakashyn** [comment]
e làm đc cái đấy r, đã add vào đc db cái link của nó dưới dạng [a,b,c].
vấn đề là e ko muốn bulk insert kiểu đấy, rất khó manage về sau. Nên e muốn từng cái a,b,c kia sẽ là 1 record riêng

**Comment by bakashyn** [comment]
ý định của e là foreach cái array input file, xong save lần lượt mà đang bị lỗi và e cũng ko hiểu tại sao :'(

**Comment by quyetdc** [comment]
a đọc code thì mỗi ảnh up lên = 1 picture? error là gì em

**Comment by quyetdc** [comment]
như vậy thì link của picture sẽ là string nhé, mỗi picture chỉ gồm 1 link đúng ko

**Comment by bakashyn** [comment]
undefined method `save' for nil:NilClass

**Comment by bakashyn** [comment]
e nói thế này cho dễ hiểu, 
h e muốn upload 70 cái ảnh 1 lúc, trả về 70 link, e muốn mỗi link là 1 record chứ ko phải 1 record vs array 70 cái link :\

**Comment by quyetdc** [comment]
uk , a hieu y em roi.

Em tao model picture, co link:string
link -> Picture uploader

Khi em tao 1 cai Portfolio, em tao dong thoi 70 cai picture khi select 70 anh cho 70 link cua dong pictures do (a nho ko nham thi su dung accept nested attributes, hoac truyen param bthg len cung duoc), gan picture vua tao cho portfolio

Hien em lam picture co link:text, ko dung vs gem uploader no huong dan

**Comment by bakashyn** [comment]
link của e là varchar(255) ngay từ đầu rồi.

**Comment by quyetdc** [comment]
co 1 cach la em push code len day di, de a vs cac ban clone ve fix thu xem :p

**Comment by bakashyn** [comment]
e quằn quaị vs các bô lão trên stack thì fix đc r =)). params[:picture][:link] ms đúng, ở trên thiếu picture nên hàm if ko chạy nên bị nil method save

**Comment by quyetdc** [comment]
[![LGTM](http://lgtm.in/p/I8T0fYsPp)](http://lgtm.in/i/I8T0fYsPp)

LOL
